[changelog]
header = """
# Changelog

Все значимые изменения в проекте документируются в этом файле.\n
Формат основан на [Keep a Changelog](https://keepachangelog.com/ru/1.1.0/),  
а версионирование следует [Semantic Versioning](https://semver.org/lang/ru/).\n
"""

body = """
{% if version %}\n## [{{ version | trim_start_matches(pat="v") }}] — {{ timestamp | date(format="%Y-%m-%d") }}\n{% else %}\n## [Unreleased]\n{% endif %}\n\n{% for group, commits in commits | group_by(attribute="group") %}\n### {{ group | striptags | trim | upper_first }}\n\n{% for commit in commits %}\n- {{ commit.message | upper_first }}\n{% endfor %}\n{% endfor %}\n"""

# Скрыть паттерны коммитов из CHANGELOG
commit_preprocessors = [
  { pattern = "^(feat|fix|docs|style|refactor|perf|test|chore|ci|build|revert)(\\(.*\\))?!?:", replace = "" },
]

commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^docs", group = "Documentation" },
  { message = "^style", group = "Styling" },
  { message = "^refactor", group = "Changed" },
  { message = "^perf", group = "Performance" },
  { message = "^test", group = "Testing" },
  { message = "^chore", group = "Chores" },
  { message = "^ci", group = "CI/CD" },
  { message = "^build", group = "Build" },
  { message = "^revert", group = "Reverted" },
]

filter_commits = false
tag_pattern = "v[0-9]*"
sort_commits = "oldest"
